# Generated by Django 6.0.3 on 2026-04-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GPUFPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gpu_name", models.CharField(max_length=255)),
                ("game", models.CharField(max_length=255)),
                ("resolution", models.CharField(max_length=64)),
                ("fps_min", models.IntegerField()),
                ("fps_max", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
