# Generated by Django 4.2.29 on 2026-05-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequest',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='admin_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='contact',
            field=models.CharField(blank=True, help_text='Телефон, Telegram или другой удобный способ связи', max_length=120, verbose_name='Дополнительный контакт'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('done', 'Обработано')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='subject',
            field=models.CharField(default='Без темы', max_length=140, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='topic',
            field=models.CharField(choices=[('question', 'Вопрос по работе сайта'), ('bug', 'Нашел ошибку'), ('data', 'Проблема с ценами или характеристиками'), ('feature', 'Предложение по улучшению'), ('other', 'Другое')], max_length=20, verbose_name='Тема'),
        ),
    ]
